apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "argo-workflows"
  namespace: "argo-workflows"
spec:
  # Apply to all pods in this namespace
  endpointSelector: {}
  egress:
    # Outbound to k8s DNS to look up SeaweedFS service IP only
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: seaweedfs-s3.seaweedfs.svc.cluster.local
    # Outbound to seaweedfs-s3 service for data I/O
    - toServices:
        - k8sService:
            namespace: seaweedfs
            serviceName: seaweedfs-s3
    # Outbound to k8s API
    # For informing that a job has completed
    - toEntities:
        - kube-apiserver
  # Allow no ingress
  ingress:
    - {}
