apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "argo-workflows"
  namespace: "argo-workflows"
spec:
  endpointSelector: {}
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: minio.argo-artifacts.svc.cluster.local
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: argo-artifacts
            v1.min.io/pool: argo-artifacts-pool-0
    - toServices:
        - k8sService:
            namespace: argo-artifacts
            serviceName: minio
        - k8sService:
            namespace: argo-artifacts
            serviceName: argo-artifacts-hl
