---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "harbor-frontend"
  namespace: "harbor"
spec:
  endpointSelector:
    matchLabels:
      app: harbor
      component: nginx
  egress: []
  ingress:
    # Allow connection to web frontend from internet
    - fromEntities:
        - world
      toPorts:
        - ports:
            - port: "80"
        - ports:
            - port: "433"
