apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: harbor-kube-dns
  namespace: harbor
spec:
  # Apply to all pods in this namespace
  endpointSelector: {}
  # Deny all ingress by default
  ingress: []
  egress:
    # Outbound to k8s DNS to look up IPs
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: harbor-allow-databases
  namespace: harbor
spec:
  # Apply to all pods in this namespace that have the label app.kubernetes.io/name: harbor
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: harbor
  # Allow ingress and egress to/from the database pods to/from all Harbor pods
  # Port 6379 is for Redis
  # Port 5432 is for PostgreSQL
  egress:
    - toEndpoints:
      - matchLabels:
          app.kubernetes.io/name: harbor
      toPorts:
        - ports:
          - port: "6379"
            protocol: TCP
          - port: "5432"
            protocol: TCP
  ingress:
    - fromEndpoints:
      - matchLabels:
          app.kubernetes.io/name: harbor
      toPorts:
        - ports:
          - port: "6379"
            protocol: TCP
          - port: "5432"
            protocol: TCP
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: harbor-allow-ingress
  namespace: harbor
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: harbor
      component: nginx
  ingress:
    - fromEndpoints:
      - matchLabels:
          app.kubernetes.io/name: ingress-nginx
          k8s:io.kubernetes.pod.namespace: ingress-nginx
      toPorts:
        - ports:
          - port: "8080"
            protocol: TCP
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: harbor-allow-readiness-probe
  namespace: harbor
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: harbor
  ingress:
    - fromEntities:
        - host
      toPorts:
        - ports:
          - port: "8080"
            protocol: TCP
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: harbor-allow-webui
  namespace: harbor
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: harbor
  egress:
    - toEndpoints:
      - matchLabels:
          app.kubernetes.io/name: harbor
      toPorts:
        - ports:
          - port: "8080"
            protocol: TCP
  ingress:
    - fromEndpoints:
      - matchLabels:
          app.kubernetes.io/name: harbor
      toPorts:
        - ports:
          - port: "8080"
            protocol: TCP
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: harbor-allow-registry
  namespace: harbor
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: harbor
  egress:
    - toEndpoints:
      - matchLabels:
          app.kubernetes.io/name: harbor
      toPorts:
        - ports:
          - port: "5000"
            protocol: TCP
  ingress:
    - fromEndpoints:
      - matchLabels:
          app.kubernetes.io/name: harbor
      toPorts:
        - ports:
          - port: "5000"
            protocol: TCP
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: harbor-allow-host-pull
  namespace: harbor
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: harbor
  ingress:
    - fromEntities:
        - host
        - remote-node
      toPorts:
        - ports:
          - port: "8080"
            protocol: TCP
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: harbor-allow-egress-to-registries
  namespace: harbor
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: harbor
      component: core
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchName: "ghcr.io"
              - matchName: "hub.docker.com"
              - matchName: "registry-1.docker.io"
              - matchName: "production.cloudflare.docker.com"
    - toFQDNs:
      - matchName: "ghcr.io"
      - matchName: "hub.docker.com"
      - matchName: "registry-1.docker.io"
      - matchName: "production.cloudflare.docker.com"
