---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "harbor-frontend"
  namespace: "harbor"
spec:
  endpointSelector:
    matchLabels:
      app: harbor
      component: nginx
  egress: []
  ingress:
    # Allow connection to web frontend from internet and cluster
    - fromEntities:
        - world
        - host
      toPorts:
        - ports:
            - port: "80"
        - ports:
            - port: "433"
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "harbor-internal"
  namespace: "harbor"
spec:
  endpointSelector: {}
  ingress:
    # Allow ingress from all other pods in this namespace
    - fromEndpoints:
        - {}
  egress:
    # Allow egress to all other pods in this namespace
    - toEndpoints:
        - {}
---

apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "harbor-registry"
  namespace: "harbor"
spec:
  endpointSelector:
    matchLabels:
      app: harbor
      component: registry
  egress: []
  ingress:
    # Allow ingress from external and nodes to harbor registry
    - fromEntities:
        - world
        - host
      toPorts:
        - ports:
            - port: "5000"
