apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-prometheus
  namespace: ingress-nginx
spec:
  endpointSelector:
    matchLabels:
      k8s:app.kubernetes.io/name: ingress-nginx
      k8s:app.kubernetes.io/component: controller
  ingress:
    - fromEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: monitoring-system
          k8s:app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
          - port: "10254"
            protocol: TCP
