apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-desktop
spec:
  runStrategy: Manual
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: ubuntu-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
      source:
        http:
          url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu-desktop
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavoldisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 4096M
            cpu: "2"
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: ubuntu-dv
        name: datavoldisk
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: ubuntu
            chpasswd: { expire: False }
            ssh_pwauth: True
            packages:
              - xfce4
              - xfce4-goodies
              - xrdp
            runcmd:
              - echo xfce4.session >~/.xsession
              - systemctl enable xrdp
              - systemctl start xrdp
