## Custom resource configuration
crds:
  keep: false
namespaceOverride: "argo"
server:
  secure: true
  authModes:
    - sso
  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/proxy-body-size: 100M
      ingress.kubernetes.io/app-root: "/"
      cert-manager.io/issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingressClassName: "nginx"
    hosts:
      - <your-domain-here>
    pathType: ImplementationSpecific
    tls:
      - secretName: argo-ingress-tls-letsencrypt
        hosts:
          - <your-domain-here>
  sso:
    enabled: true
    issuer: https://login.microsoftonline.com/<tenant-id>/v2.0
    clientId:
      name: argo-server-sso
      key: client-id
    clientSecret:
      name: argo-server-sso
      key: client-secret
    redirectUrl: "https://<your-domain-here>/oauth2/callback"
    scopes:
      - https://graph.microsoft.com/User.Read
      - https://graph.microsoft.com/Group.Read.All
      - email
artifactRepository:
  s3:
    bucket: argo-artifacts
    endpoint: minio.argo-artifacts.svc.cluster.local:80
    region: eu-west-2
    accessKeySecret:
      name: argo-artifacts-minio
      key: accesskey
    secretKeySecret:
      name: argo-artifacts-minio
      key: secretkey
    insecure: true