# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing

# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_crds.acme as __acme

    acme = __acme
    import pulumi_crds.cert_manager as __cert_manager

    cert_manager = __cert_manager
    import pulumi_crds.meta as __meta

    meta = __meta
else:
    acme = _utilities.lazy_import("pulumi_crds.acme")
    cert_manager = _utilities.lazy_import("pulumi_crds.cert_manager")
    meta = _utilities.lazy_import("pulumi_crds.meta")

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "crds",
  "mod": "acme.cert-manager.io/v1",
  "fqn": "pulumi_crds.acme.v1",
  "classes": {
   "kubernetes:acme.cert-manager.io/v1:Challenge": "Challenge",
   "kubernetes:acme.cert-manager.io/v1:ChallengeList": "ChallengeList",
   "kubernetes:acme.cert-manager.io/v1:ChallengePatch": "ChallengePatch",
   "kubernetes:acme.cert-manager.io/v1:Order": "Order",
   "kubernetes:acme.cert-manager.io/v1:OrderList": "OrderList",
   "kubernetes:acme.cert-manager.io/v1:OrderPatch": "OrderPatch"
  }
 },
 {
  "pkg": "crds",
  "mod": "cert-manager.io/v1",
  "fqn": "pulumi_crds.cert_manager.v1",
  "classes": {
   "kubernetes:cert-manager.io/v1:Certificate": "Certificate",
   "kubernetes:cert-manager.io/v1:CertificateList": "CertificateList",
   "kubernetes:cert-manager.io/v1:CertificatePatch": "CertificatePatch",
   "kubernetes:cert-manager.io/v1:CertificateRequest": "CertificateRequest",
   "kubernetes:cert-manager.io/v1:CertificateRequestList": "CertificateRequestList",
   "kubernetes:cert-manager.io/v1:CertificateRequestPatch": "CertificateRequestPatch",
   "kubernetes:cert-manager.io/v1:ClusterIssuer": "ClusterIssuer",
   "kubernetes:cert-manager.io/v1:ClusterIssuerList": "ClusterIssuerList",
   "kubernetes:cert-manager.io/v1:ClusterIssuerPatch": "ClusterIssuerPatch",
   "kubernetes:cert-manager.io/v1:Issuer": "Issuer",
   "kubernetes:cert-manager.io/v1:IssuerList": "IssuerList",
   "kubernetes:cert-manager.io/v1:IssuerPatch": "IssuerPatch"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "crds",
  "token": "pulumi:providers:kubernetes",
  "fqn": "pulumi_crds",
  "class": "Provider"
 }
]
""",
)
