apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-configuration
  namespace: $namespace
  labels:
    app: minio
data:
  setup.sh: |
    echo "Creating policies now"
    for policy in /tmp/scripts/*.json; do
      echo "Creating policy $$policy"
      mc --insecure admin policy create argoartifacts $$(basename $$policy) $$policy
      echo "Policy $$(basename $$policy) created"
    done
  read-only-ingress.json: |
    {
      "version": "2012-10-17",
      "statement": [
        {
          "Effect": "Allow",
          "action": [
            "s3:GetBucketLocation",
            "s3:GetObject",
            "s3:ListBucket"
          ],
          "resource": [
            "arn:aws:s3:::ingress",
            "arn:aws:s3:::ingress/*"
          ]
        }
      ]
    }
  read-only-sensitive-ingress.json: |
    {
      "version": "2012-10-17",
      "statement": [
        {
          "Effect": "Allow",
          "action": [
            "s3:GetBucketLocation",
            "s3:GetObject",
            "s3:ListBucket"
          ],
          "resource": [
            "arn:aws:s3:::sensitive-ingress",
            "arn:aws:s3:::sensitive-ingress/*"
          ]
        }
      ]
    }
  write-only-ready-for-review.json: |
    {
      "version": "2012-10-17",
      "statement": [
        {
          "Effect": "Allow",
          "action": [
            "s3:PutObject"
          ],
          "resource": [
            "arn:aws:s3:::ready-for-review",
            "arn:aws:s3:::ready-for-review/*"
          ]
        }
      ]
    }
  write-only-ready-for-export.json: |
    {
      "version": "2012-10-17",
      "statement": [
        {
          "Effect": "Allow",
          "action": [
            "s3:PutObject"
          ],
          "resource": [
            "arn:aws:s3:::ready-for-export",
            "arn:aws:s3:::ready-for-export/*"
          ]
        }
      ]
    }
