# Default values for kv-single-vm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
  disksize: 30Gi

vm:
  runStrategy: Manual
  namespace: default
  name: ubuntu-lite
  resources:
    memory: 2048M
    cpu: "2"
