---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kv-single-vm.fullname" . }}
spec:
  selector:
    kubevirt.io/domain: {{ include "kv-single-vm.fullname" . }}
  ports:
  - name: rdp
    port: 3389
    targetPort: 3389
    protocol : TCP
  type: ClusterIP
