apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: deny-all-traffic
  namespace: fridge-api
spec:
  endpointSelector: {}
  ingress:
    - {}
  egress:
    - {}
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-argo-server-traffic
  namespace: fridge-api
spec:
  endpointSelector:
    matchLabels:
      app: fridge-api-server
  ingress:
    - fromEndpoints:
      - matchLabels:
          app: server
          k8s:io.kubernetes.pod.namespace: argo-server
      toPorts:
        - ports:
          - port: "2746"
            protocol: TCP
  egress:
    - toEndpoints:
      - matchLabels:
          app: server
          k8s:io.kubernetes.pod.namespace: argo-server
      toPorts:
        - ports:
          - port: "2746"
            protocol: TCP
