expose:
  type: clusterIP
  tls:
    enabled: false
    certSource: none
    secret:
      secretName: harbor-ingress-tls
persistence:
  persistentVolumeClaim:
    registry:
      storageClass: "longhorn-storage"
      accessMode: ReadWriteMany
    jobservice:
      jobLog:
        storageClass: "longhorn-storage"
        accessMode: ReadWriteMany
