apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      k8s-app: metrics-server
  # The metrics-server collects realtime metrics from kubelets
  # and provides them to the Kubernetes API server for use in autoscaling
  # https://kubernetes-sigs.github.io/metrics-server/
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
          - port: "6443"
            protocol: ANY
    - toEntities:
        - host
      toPorts:
        - ports:
          - port: "10250"
            protocol: TCP
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: local-path-provisioner
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      app: local-path-provisioner
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
          - port: "6443"
            protocol: ANY
