config:
  fridge:azure_disk_encryption_set: fridge-disk-encryption-set
  fridge:azure_subscription_id: "36cfe11d-bfcd-4dce-9b70-c3905a4f3d01"
  fridge:azure_resource_group: fridge-multiple
  fridge:base_fqdn: aks.fridge.develop.turingsafehaven.ac.uk
  fridge:harbor_admin_password:
    secure: v1:3+jAcVhe/3xj57pG:EEgytR6DgCOZqJrJsoHyLNEwWPOLxW5/
  fridge:harbor_ip: 10.0.50.50
  fridge:harbor_fqdn_prefix: harbor
  fridge:lets_encrypt_email: safehavendevs@turing.ac.uk
  fridge:minio_root_user:
    secure: v1:7RTVpai0RPBKdOcU:ZxD8eVRGaNec9SrCyfSWx1JP91zz55PL
  fridge:minio_root_password:
    secure: v1:Cre1kldv85pjorE8:RBF5XK/QC+b4yRe9Kben7uOqz5OwV+d/MvBE
  fridge:minio_pool_size: 30Gi
  fridge:tls_environment: staging
  fridge:k8s_env: AKS
  pulumi:autonaming:
    mode: verbatim
  kubernetes:context: cluster
  fridge:fridge_api_admin:
    secure: v1:nn2LgdxeGCv5c0Lv:pr4uv23iVaHqcZ9cq0FqZnNtKNaRCciG
  fridge:fridge_api_password:
    secure: v1:x/BGXr+SaRLFlvZf:KN9s8Tu7wbRc/Pk3yOBv6Jp0VHsjp64UXZw=
encryptionsalt: v1:Yui0lUJOPMA=:v1:nZMkxSs5zpUr595r:XfbqFspmQv0wIkHO37kCREPW9o50nw==
